site_name: Tinker Documentation
site_description: Documentation for the Tinker project
site_author: Tinker Team

theme:
  name: gitbook

plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.9.1/dist/mermaid.esm.min.mjs
      arguments:
        securityLevel: 'loose'
        theme: 'default'
        flowchart:
          useMaxWidth: true
          htmlLabels: true
        journey:
          useMaxWidth: true
        sequence:
          useMaxWidth: true
        class:
          useMaxWidth: true
        state:
          useMaxWidth: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Event Storming: 1_event_storming.md
  - User Journeys: 2_user_journeys.md
  - Touch Points & Screens: 3_touch_points_screens.md
  - Screen Mockups: 4_screen_mockups.md
  - Screen Variations: 5_screen_variations.md
  - Summary: 6_summary.md
  - Mermaid Examples: mermaid_example.md
